[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bice"
version = "0.3.9"
description = "Numerical continuation and bifurcation package"
readme = "doc/pypi-description.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
  {name = "Simon Hartmann", email = "s.hartmann@wwu.de"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "findiff",
    "numdifftools",
]

[project.urls]
"Homepage" = "https://gitlab.com/simon123h/bice"

[tool.setuptools.packages.find]
where = ["."]
include = ["bice*"]
